apiVersion: v1
kind: Service
metadata:
  name: calwc-esc-server
  labels:
    app: calwc-esc-server
spec:
  type: ClusterIP
  selector:
    app: calwc-esc-server
  ports:
  - name: http-calwc-esc-server
    port: 80
    protocol: TCP
    targetPort: 6738
