apiVersion: v1
kind: Service
metadata:
  name: calwc-esc
  labels:
    app: calwc-esc
spec:
  type: ClusterIP
  selector:
    app: calwc-esc
  ports:
  - name: http-calwc-esc
    port: 80
    protocol: TCP
    targetPort: 6738
