apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: armyapp-dev
resources:
  - ../../base
  - istio.yml
patches:
  - path: deployment.yml
images:
  - name: calwc-esc
    newName: armycontainersdev.azurecr.io/calwc-esc
configMapGenerator:
  - name: calwc-esc-config
    envs:
      - config.properties
