apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: armyapp
resources:
  - ../../base
  - istio.yml
  - secrets.yml
patches:
  - path: deployment.yml
images:
  - name: army-app-staff-checks-server
    newName: armycontainersdev.azurecr.io/army-app-staff-checks-server
configMapGenerator:
  - name: staff-checks-config
    envs:
      - config.properties
