# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: army-app-staff-checks-secret-provider
spec:
  provider: azure
  secretObjects:
    - secretName: army-app-staff-checks-secret
      type: Opaque
      data:
        - objectName: staffchecksdbconnection
          key: staffchecksdbconnection
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true' # Set to true for using managed identity
    userAssignedIdentityID: 3e28633e-56cd-4768-bba4-5d589d98b9f9 # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: NDDNHQCAKeyProdVault
    cloudName: '' # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: staffchecksdbconnection
          objectType: secret
    tenantId: 325b4494-1587-40d5-bb31-8b660b7f1038 # The tenant ID of the key vault
    syncSecret: 'true'
    enableSecretRotation: 'true'
